global using CvBuilder.Core.Interfaces.IServices;
global using CvBuilder.Core.IoC;
global using CvBuilder.Core.UserCases.Commands.AddAboutMeToUser;
global using CvBuilder.Core.UserCases.Commands.AddSkillToUser;
global using CvBuilder.Core.UserCases.Commands.AddWorkExperienceToUser;
global using CvBuilder.Core.UserCases.Commands.CreateUser;
global using CvBuilder.Core.UserCases.Commands.LoginUser;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;